FROM debian:bullseye-slim

RUN apt-get update && apt-get install -y curl git python3 python3-dev python3-pip apt-transport-https curl gnupg
RUN curl -fsSL https://bazel.build/bazel-release.pub.gpg | gpg --dearmor >bazel-archive-keyring.gpg && \
    mv bazel-archive-keyring.gpg /usr/share/keyrings && \
    echo "deb [arch=amd64 signed-by=/usr/share/keyrings/bazel-archive-keyring.gpg] https://storage.googleapis.com/bazel-apt stable jdk1.8" | tee /etc/apt/sources.list.d/bazel.list && \
    apt-get update && apt-get install -y bazel bazel-5.0.0

RUN pip3 install --upgrade pip && \
    pip install -U --user pip numpy wheel packaging requests opt_einsum && \
    pip install -U --user keras_preprocessing --no-deps

WORKDIR /tensorflow
VOLUME /tensorflow/output

COPY entrypoint.sh /tensorflow/entrypoint.sh
RUN chmod +x /tensorflow/entrypoint.sh

ENTRYPOINT ["/tensorflow/entrypoint.sh"]

CMD ["sh"]